Разметка всех страниц.
htmlacademy-htmlcss/2103387-sedona-36 pull request #2
Opened 2023-01-28 14:00 UTC by Fiji13

2023-01-28 20:09 UTC, kenakula requested changes
Отличная работа. Нужны небольшие правки

2023-01-28 20:09 UTC, kenakula commented on catalog.html
> +                <span class="visually-hidden">Корзина</span>
больше похоже на Избранное

2023-01-28 20:09 UTC, kenakula commented on catalog.html
> +            </li>
Можно и так, но я бы вынес логотип за пределы списка навигации, он все же сильно отличается и визуально и по своей сущности от ссылок меню

2023-01-29 10:52 UTC, Fiji13 commented on catalog.html
> +                <span class="visually-hidden">Корзина</span>
Спасибо! Поправила.

2023-01-29 10:52 UTC, Fiji13 commented on catalog.html
> +            </li>
Сделала.

2023-01-29 10:58 UTC, merged